language: bash

notifications:
  email: false

addons:
  apt:
    packages:
      - build-essential
      - subversion
      - fakeroot
      - gawk
      - gnupg

env:
  global:
  - OPENWRT_VERSION=18.06.1
  - PACKAGES=
  matrix:
  - BUILD_ARCH=x86_64

script:
  - ./build.sh --arch "$BUILD_ARCH" --version "$OPENWRT_VERSION" --packages "$PACKAGES"

before_deploy:
  git fetch --tags

deploy:
  provider: releases
  api_key:
    secure: dNGBMhGznvVpv8hVI7+B+Kr4mrRU0yNGjahjhQ+VMwfm9MtY4RJUj/ePAPHOZt6b76TrYhxcfEsI0QFHOSQfb3jvv5TBGvmNv6OR0gBR1UeIFPoeLJTUYeHTJCaPV/x67C//ef3tdSkHCrfsTdCw0CNDJzWsoK5ZvIwoa0IQAV5KrnjHT9W1Lu6821vshI62ZNyE6K0/7Ej+CXLHiTnH89lWoTAcqPiYl8pMCQ0Fu9+LrWbm9DpWyDyCsDQ9MdKefLG5izlSHXB4zMiu1/J/e8vOlh9LJw4m53PK4sGkrXegF7mgQZ+rOjZ4iqO31R/7almfGXXWFaqXdD+OzOhcUB7SitbOoIKOe0M9fZpuB6Do3p9r+KOomfAqklJ6SnFQmwqgD7LILW3d80+5mA440ZrwwJ2x42pbtsxALYGPvnzLndiAil64fh0lEJI2fQ7aBko9pId4hrMXmrVhq/IAI0KsbrgR7+RNK+xQSSFcLi8vu0vzjoSkcI0voysYq0mVoDvC0HacAywdqACRs1mdWkYx8uq1NHx7Iwgj5CtTmbO08AtK3S3KS//gzOhTmwzafMi1AcFLRKc8h4PTpo1O+eT0/nTQJGF8R+6gPfhG6aLb/QlepIt3UF1pS63IAIC81cKB7DEB/3RGB41M9bxrd81bJgo+NMdCmvddPA6BLeo=
  file: bin/openwrt-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: DavBfr/lxd-openwrt
    tags: true
